version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notesapp-app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: notes_app
      DB_USERNAME: user
      DB_PASSWORD: password
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - vendor:/app/vendor
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: notesapp-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app
    restart: unless-stopped


  db:
    image: mysql:8.0
    container_name: notesapp-db
    environment:
      MYSQL_DATABASE: notes_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  vendor: