version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: note-app
    container_name: note-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: note_app
      DB_USERNAME: laravel
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: note-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: note_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
